server:
  port: 8080

spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:database-dialog-changelog.xml
    default_schema: ${DB_SCHEMA:dialog}

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:5432/skillbox
    username: ${DB_USERNAME:dialog}
    password: ${DB_PASSWORD:dialog}
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: ${DB_SCHEMA:dialog}
    open-in-view: false

kafka:
  bootstrap-servers: kafka-service.skillbox-alpha-kafka:9092
  consumer:
    group-id: dialog.1
    concurrency: 3
    max.poll.interval.ms: 1000
    spring.json.trusted.packages: ru.skillbox.diplom.group35.*
  producer:
    retries: 3
  topic:
    partition-count: 3
    replication-factor: 1
    reply: t.dialog.message.out
    request: t.dialog.message.in

logging:
  level:
    org.springframework: info
    org.apache.kafka.clients.producer: ERROR