server:
  port: 8085

spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:database-dialog-changelog.xml
    default_schema: dialog

  datasource:
    url: jdbc:postgresql://localhost:5432/skillbox
    username: dialog
    password: dialog
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: dialog
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: app.1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  topic:
    account: topic-dialog

logging:
  level:
    org.springframework: info