apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-dialog
data:
  application.yml: |-

    server:
      port: 8080

    spring:
      liquibase:
        enabled: true
        drop-first: false
        change-log: classpath:database-dialog-changelog.xml
        default_schema: dialog

      datasource:
        url: jdbc:postgresql://postgres-service:5432/skillbox
        username: dialog
        password: dialog
        driverClassName: org.postgresql.Driver

      jpa:
        show-sql: false
        hibernate:
          ddl-auto: none
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQL10Dialect
            format_sql: true
            default_schema: dialog
        open-in-view: false